### ISSUE TITLE
Incorrect results with jax >0.3.20

### ISSUE THREAD

**Issue by astanziola** [ucl-bug/holab#3]
With the newest versions of jax the answers are simply wrong. 
On top of this, the issue of constant-folding ( #2 ) is much worse on newest jax versions, potentially related with the patch released to fix https://github.com/google/jax/issues/12789

Should try to do a minimal example, to file a bug in the upstream libraries (jwave, jaxdf or jax itself)

**Comment by hawkinsp** [comment]
This is apparently fixed with JAX 0.4.11 or newer.
